# Generated by Django 3.1.6 on 2021-02-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cover',
            new_name='image',
        ),
    ]
